apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: we93sg4uk-java-springboot
  janus-idp.io/tekton: we93sg4uk-java-springboot
  backstage.io/kubernetes-id: we93sg4uk-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: we93sg4uk-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
